### ISSUE TITLE
Lost old feeds in update

### ISSUE THREAD

**Issue by ahstro** [nextcloud/news-updater#14]
I recently upgraded Nextcloud to version 13 and now, my old feeds seem to be gone from the web UI. I still have them in the News android app, but refreshing/syncing on either side fails to bring them into the web UI.

If I go to `web.ui/apps/news/#/items/folders/1`, the folder shows up in the sidebar, with the correct name, but without any content. This works for all folders I had before the update.

Refreshing the android app updates the feeds so I get new entries, but like I said, nothing happens in the web UI.

**Comment by BernhardPosselt** [comment]
Wrong repo
