### ISSUE TITLE
News updater ERROR PCNTL

### ISSUE THREAD

**Issue by Darkmagister** [nextcloud/news-updater#17]
Hello, i've seend that i'm not the first one with this issue but i'm not able to find a solution in the other answer, so i'm trying to execute the python news updater but i get this error, 
i've tried with phpinfo and i see the module pcntl, so i don't know why this is happening, also i can not recompile the php, so there are any ways to disable this error and let's python continue it's job?

php: 7.3.1
news-updater from pip3: 10.0.1

here the error:
Nextcloud News Updater - ERROR - Could not parse given JSON: The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php

**Comment by BernhardPosselt** [comment]
The issue is that PHP spits out text which messes up the JSON, so on the updater's side there's nothing you can do here. You could try to silence the error warning in your Nextcloud install but you'll have to Google that on your own (no idea).

**Comment by Darkmagister** [comment]
ok, so I have to find by myself a way to silence the warning I think, I've tried with disable warning in PHP.ini but with no success :(

**Comment by BernhardPosselt** [comment]
Please install the pcntl module as listed in the exception
