### ISSUE TITLE
11.0.0: 'NoneType' object has no attribute 'before_cleanup_url'

### ISSUE THREAD

**Issue by birros** [nextcloud/news-updater#25]
Hello, yesterday I updated my infra nextcloud, I found the following error in the logs of the news-updater service.

I quickly looked in the sources but I'm not a python expert.

I hope this issue will be useful. Thanks for your work 🙂

## Logs

```
2020-10-21 10:19:47,746 - Nextcloud News Updater - ERROR - 'NoneType' object has no attribute 'before_cleanup_url': Trying again in 30 seconds
Traceback (most recent call last):
  File "/usr/lib/python/site-packages/nextcloud_news_updater/api/updater.py", line 69, in run
    self.before_update()
  File "/usr/lib/python/site-packages/nextcloud_news_updater/api/web.py", line 75, in before_update
    'Calling before update url:  %s' % self.api.before_cleanup_url)
AttributeError: 'NoneType' object has no attribute 'before_cleanup_url'
```

## Dockerfile

```
FROM python:3-alpine

RUN pip install --upgrade nextcloud_news_updater --prefix=/usr

RUN ln -s /usr/lib/python$(python -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))') /usr/lib/python

ENV PYTHONPATH /usr/lib/python/site-packages

CMD nextcloud-news-updater ${NEXTCLOUD_URL} --user ${NEXTCLOUD_ADMIN_USER} --password ${NEXTCLOUD_ADMIN_PASSWORD} --loglevel info
```

## Versions

- **python:3-alpine**: sha256:f624846577d26bfe43a4b5db5a48c4c0ca1e410425cb8b662ca6ac9e35f50f7a
- **nextcloud_news_updater**: 11.0.0
- **nextcloud:fpm-alpine**: sha256:68ca963489bd36a18096e700350e3eaddc9a98fbc7bfde090340e6b65631c12c

**Comment by BernhardPosselt** [comment]
You need the correct API level, see https://github.com/nextcloud/news-updater/pull/23

**Comment by BernhardPosselt** [comment]
Likely v1-2 in your case

**Comment by birros** [comment]
Solved, i added `--apilevel v1-2`

Thanks for your reactivity 👍
