### ISSUE TITLE
Documentation for config-file

### ISSUE THREAD

**Issue by davralin** [nextcloud/news-updater#27]
Some example config-files is "hidden" under `master/tests/nextcloud_news_updater/configs`.

Documentation for options lists there being an example under `bin/example_config.ini`.

Should these paths be in sync?

**Comment by BernhardPosselt** [comment]
Nope, that file is used for tests only, is no example and shouldn't be used in production  ;)

**Comment by davralin** [comment]
Well, the documentation is still wrong - there's no example under `bin/example_config.ini`.

**Comment by BernhardPosselt** [comment]
Ah, thanks! Yep, will remove that line because it's in the next paragraph in the README

**Comment by davralin** [comment]
Well, now I feel silly for not seeing that...
