### ISSUE TITLE
[Question/ Request] Nextcloud Snap Support

### ISSUE THREAD

**Issue by zero77** [nextcloud/news-updater#33]
Sorry if this is documented already but, is it possible to use news-updater with nextcloud snap package.
If not is this something that could be added, thanks.

**Comment by BernhardPosselt** [comment]
Feel free to do it, we don't build packages but leave that up to package maintainers. Otherwise we'd end up with having to maintain docker, debian, ebuilds, pkgbuilds, snaps, flatpaks, etc
