### ISSUE TITLE
403 Errors when retriving feeds

### ISSUE THREAD

**Issue by bradgranath2** [nextcloud/news-updater#35]
I'm getting a 403 error when retrieving some feeds.  What are the headers that are sent with the request?

**Comment by BernhardPosselt** [comment]
Your user and password via basic auth.

**Comment by BernhardPosselt** [comment]
Needs to be an admin fyi :)

**Comment by bradgranath2** [comment]
So, no User-Agent or other such that might be expected by a firewall trying to suss out crawler requests?

What do you mean "Be Admin"?

The feed in question is open; no auth required.

**Comment by BernhardPosselt** [comment]
Ah you are probably filing this in the wrong repo, use https://github.com/nextcloud/news
