### ISSUE TITLE
NCHub News app on shared host

### ISSUE THREAD

**Issue by CSchaefer70** [nextcloud/news-updater#36]
I installed the News App on an instance of NextCloud Hub v 20.0.7 which is on a Shared Host.  The app runs but gives warnings about not being able to update.  The "admin news" section does have the cron settings enabled.  I do not think I can use the methods [described](https://github.com/nextcloud/news-updater) as I do not have access to the root.

I can create a cron job on the server.  What path and code should I use to keep the news service running and refreshing?  and into which directory?  Is this possible on a shared server?  Is there any other way to make this work?

![news warning](https://user-images.githubusercontent.com/26978180/107361104-da06ed80-6aa4-11eb-842b-45db6c52d16f.jpg)
![newscron](https://user-images.githubusercontent.com/26978180/107361107-da9f8400-6aa4-11eb-8924-c8425ef742bc.jpg)

**Comment by CSchaefer70** [comment]
Hmmm... maybe a fix... changed the NextCloud "admin/basic settings..." to allow "cron" instead of AJAX.  Warning gone.  However, pages will only update every 5 minutes.  I suppose this is OK.

Still, I wonder if I could implement a CRON on the server directly... no documentation/understanding of file placement/directory to make this happen.  Also, maybe no any better then letting NCHub manage?

I'm wondering but but always lost.

![cron](https://user-images.githubusercontent.com/26978180/107413433-bd87a700-6ade-11eb-82c2-3693263be04f.jpg)

**Comment by BernhardPosselt** [comment]
You should ask that on the news repository, see https://github.com/nextcloud/news
