### ISSUE TITLE
pypi package author contact

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/news-updater#45]
Hi @BernhardPosselt we received a report that the email domain you used to register the package is up for sale. Is this all discontinued, or is it a mistake?

**Comment by BernhardPosselt** [comment]
Just checked, it's a gmail email address that I still own so not sure what's up. I did indeed get rid of the bernhard-posselt.com domain but that one should not be associated with the pypi account

**Comment by nickvergessen** [comment]
https://pypi.org/project/nextcloud_news_updater/ and https://pypi.org/pypi/nextcloud-news-updater/json still list that old domain.
But okay then. just confusing and not an issue and I guess it would heal once you release a new package
