### ISSUE TITLE
KeyError: 'updater'

### ISSUE THREAD

**Issue by cstackpole** [nextcloud/news-updater#5]
Greetings,

Scientific Linux 7.2 fully updated. Using PHP 7.0 from the IUS repository. Nextcloud 10.0

All of the commands manually work: https://github.com/nextcloud/news-updater#using-the-cli-based-updater-fails

However, when I run it through the API it fails.

> $ sudo -u apache /bin/python3 /usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini -l error
> 2016-09-04 19:32:26,987 - Nextcloud News Updater - ERROR - 'updater': Trying again in 30 seconds
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/nextcloud_news_updater-9.0.2-py3.4.egg/nextcloud_news_updater/api/updater.py", line 70, in run
>     feeds = self.all_feeds()
>   File "/usr/lib/python3.4/site-packages/nextcloud_news_updater-9.0.2-py3.4.egg/nextcloud_news_updater/api/cli.py", line 84, in all_feeds
>     return self.api.parse_feed(feeds_json)
>   File "/usr/lib/python3.4/site-packages/nextcloud_news_updater-9.0.2-py3.4.egg/nextcloud_news_updater/api/api.py", line 22, in parse_feed
>     return self._parse_json(feed_json)
>   File "/usr/lib/python3.4/site-packages/nextcloud_news_updater-9.0.2-py3.4.egg/nextcloud_news_updater/api/cli.py", line 38, in _parse_json
>     feed_json = feed_json['updater']
> KeyError: 'updater'

I verified that my php.ini file is correct. Well, at least nextcloud seems to like it and a parser said it was valid. :-)

I have been poking at it for a while and not making much progress. I was hoping you might have a suggestion.

Thanks!

**Comment by BernhardPosselt** [comment]
Can you paste your config?

**Comment by BernhardPosselt** [comment]
I think I know the issue: use v1-2 as api level, v2 was unfortunately not finished when News 9.0.0 was released

**Comment by BernhardPosselt** [comment]
Had leftover docs which should be fixed now ;)

**Comment by cstackpole** [comment]
Fantastic! That did the trick. It runs now.

I have a follow up question. Everythings works well, however, when I start the service it works for an update then dies. Is it supposed to do that?

[root@hosta ~]# systemctl start nextcloud-news-updater
[root@hosta ~]# systemctl status nextcloud-news-updater
● nextcloud-news-updater.service
   Loaded: loaded (/etc/systemd/system/nextcloud-news-updater.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-09-05 21:07:49 CDT; 951ms ago
 Main PID: 13765 (nextcloud-news-)
   CGroup: /system.slice/nextcloud-news-updater.service
           └─13765 /bin/python3 /usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini

Sep 05 21:07:49 hosta.linux.local systemd[1]: Started nextcloud-news-updater.service.
Sep 05 21:07:49 hosta.linux.local systemd[1]: Starting nextcloud-news-updater.service...
[root@hosta ~]# systemctl status nextcloud-news-updater
● nextcloud-news-updater.service
   Loaded: loaded (/etc/systemd/system/nextcloud-news-updater.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-09-05 21:07:49 CDT; 2s ago
 Main PID: 13765 (nextcloud-news-)
   CGroup: /system.slice/nextcloud-news-updater.service
           ├─13765 /bin/python3 /usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini
           └─13771 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:all-feeds

Sep 05 21:07:49 hosta.linux.local systemd[1]: Started nextcloud-news-updater.service.
Sep 05 21:07:49 hosta.linux.local systemd[1]: Starting nextcloud-news-updater.service...
[root@hosta ~]# systemctl status nextcloud-news-updater
● nextcloud-news-updater.service
   Loaded: loaded (/etc/systemd/system/nextcloud-news-updater.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-09-05 21:07:49 CDT; 8s ago
 Main PID: 13765 (nextcloud-news-)
   CGroup: /system.slice/nextcloud-news-updater.service
           ├─13765 /bin/python3 /usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini
           ├─13817 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 13 stack
           ├─13820 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 12 stack
           ├─13821 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 11 stack
           ├─13822 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 10 stack
           ├─13824 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 9 stack
           ├─13825 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 8 stack
           ├─13826 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 7 stack
           ├─13827 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 6 stack
           ├─13830 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 5 stack
           └─13831 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 4 stack

Sep 05 21:07:49 hosta.linux.local systemd[1]: Started nextcloud-news-updater.service.
Sep 05 21:07:49 hosta.linux.local systemd[1]: Starting nextcloud-news-updater.service...
[root@hosta ~]# systemctl status nextcloud-news-updater
● nextcloud-news-updater.service
   Loaded: loaded (/etc/systemd/system/nextcloud-news-updater.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-09-05 21:07:49 CDT; 12s ago
 Main PID: 13765 (nextcloud-news-)
   CGroup: /system.slice/nextcloud-news-updater.service
           ├─13765 /bin/python3 /usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini
           ├─13848 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 3 stack
           ├─13851 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 2 stack
           └─13854 php -f /var/www/html/nextcloud/occ -c /etc/php.ini news:updater:update-feed 1 stack

Sep 05 21:07:49 hosta.linux.local systemd[1]: Started nextcloud-news-updater.service.
Sep 05 21:07:49 hosta.linux.local systemd[1]: Starting nextcloud-news-updater.service...
[root@hosta ~]# systemctl status nextcloud-news-updater
● nextcloud-news-updater.service
   Loaded: loaded (/etc/systemd/system/nextcloud-news-updater.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2016-09-05 21:08:03 CDT; 242ms ago
  Process: 13765 ExecStart=/usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini (code=exited, status=0/SUCCESS)
 Main PID: 13765 (code=exited, status=0/SUCCESS)

Sep 05 21:07:49 hosta.linux.local systemd[1]: Started nextcloud-news-updater.service.
Sep 05 21:07:49 hosta.linux.local systemd[1]: Starting nextcloud-news-updater.service...
[root@hosta ~]# systemctl status nextcloud-news-updater
● nextcloud-news-updater.service
   Loaded: loaded (/etc/systemd/system/nextcloud-news-updater.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2016-09-05 21:08:03 CDT; 5s ago
  Process: 13765 ExecStart=/usr/bin/nextcloud-news-updater -c /etc/nextcloud/news/updater.ini (code=exited, status=0/SUCCESS)
 Main PID: 13765 (code=exited, status=0/SUCCESS)

Sep 05 21:07:49 hosta.linux.local systemd[1]: Started nextcloud-news-updater.service.
Sep 05 21:07:49 hosta.linux.local systemd[1]: Starting nextcloud-news-updater.service...

**Comment by cstackpole** [comment]
BWAAAHAHAHAHA! I was digging around in the systemctl logs and setting up traps to figure out why there was no error when it stopped. Then I checked the ini file for the 5th time and realized I had set "mode = single" for testing the other day. Change that to "mode = endless" and guess what? It works!

Thank you very much for helping me with this!

**Comment by okias** [comment]
Nice! same issue, fixed thx to this thread.
