### ISSUE TITLE
Updater grabs old stories once per day

### ISSUE THREAD

**Issue by koehn** [nextcloud/news-updater#6]
I have a number of feeds that show old (like years old) articles once per day. Typically sometime overnight the updater will load articles that hit the feed years ago; I'm not sure what to do about it. Here are some feeds that exhibit this behavior: 

* http://feeds.feedburner.com/failblog
* http://minnesota.publicradio.org/tools/rss/mprnews.php

I'm running the latest News (10.1.0), NextCloud-News-Updater (installed with PIP), and NextCloud (11.0).

**Comment by BernhardPosselt** [comment]
Wrong repo, should go into News :)

The updater is a configurable program that tells the News app that it should update feed X

As for the issue: This issue can occur if the feed is either broken or does not properly handle http caching (my guess).
